github:
  is_project_page: false
title: Measuring Computational Creativity
description: A Workshop for ISEA 2020, Montreal
# remote_theme: samarsault/texture
# remote_theme: thelehhman/texture
theme: jekyll-theme-midnight
#theme: jekyll-theme-cayman
#theme: jekyll-theme-primer
