title: Measuring Computational Creativity
description:
  A Workshop for ISEA 2020, Montreal
  Sunday, October 18, 15:00pm - 19:00pm (Montreal Time, GMT-4, EST)
theme: jekyll-theme-cayman
#theme: jekyll-theme-primer
